python3 first_level.py -sc 1 -session 1 -sub 2 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 2 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 2 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 2 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 3 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 3 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 3 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 3 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 4 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 4 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 4 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 4 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 6 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 6 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 6 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 6 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 8 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 8 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 8 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 8 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 9 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 9 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 9 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 9 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 10 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 10 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 10 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 10 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 12 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 12 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 12 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 12 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 14 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 14 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 14 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 14 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 15 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 15 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 15 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 15 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 17 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 17 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 17 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 17 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 18 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 18 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 18 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 18 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 19 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 19 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 19 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 19 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 20 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 20 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 20 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 20 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 21 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 21 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 21 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 21 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 22 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 22 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 22 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 22 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 24 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 24 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 24 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 24 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 25 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 25 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 25 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 25 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 26 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 26 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 26 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 26 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 27 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 27 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 27 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 27 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 28 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 28 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 28 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 28 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 29 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 29 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 29 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 29 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 30 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 30 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 30 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 30 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 1 -sub 31 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 1 -session 2 -sub 31 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 1 -sub 31 -analysis_name first_level_bySession -bids_dir Y_data/bids
python3 first_level.py -sc 2 -session 2 -sub 31 -analysis_name first_level_bySession -bids_dir Y_data/bids
